# Generated by Django 3.2.19 on 2023-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catgory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
